<<<<<<<< HEAD:checkStatus.aspx.designer.cs
﻿//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechConnect
{


	public partial class checkStatus
	{
	}
}
========
﻿//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TechConnect
{


	public partial class forgotPassword
	{
	}
}
>>>>>>>> dadc3736eadb9317ade84224b46b6541dd9ab7cf:forgotPassword.aspx.designer.cs
